spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "abc123"
    url: jdbc:mysql://localhost:3306/qqrobot?useUnicode=true&charcterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-error-retry-attempts: 2
      time-between-connect-error-millis: 60000

  profiles:
    active: dev
simbot:
  component:
    mirai:
      deviceInfoFile: "./config/device.json"
  core:
    scan-package: priv.xds.listener

weather:
  url: https://tianqiapi.com/api