spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "w"
    url: jdbc:mysql://localhost:3306/qqrobot?useUnicode=true&charcterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: pro

mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  type-aliases-package: priv.xds.pojo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

simbot:
  component:
    mirai:
      deviceInfoFile: "./config/device.json"
  core:
    scan-package: priv.xds.listener
