spring:
  # 数据库连接的用户名和密码
  datasource:
    username: "root"
    password: "abc123"

simbot:
  core:
    # bot的用户名和密码
    bots: 1872639289:yourpassword

bot:
  sign:
    # 指定哪些群执行签到
    targetGroup: [ "700026523", "760419571" ]